# Add your Telegram bot token and trading API keys here
TELEGRAM_BOT_TOKEN ='8084222821:AAEx9fQX7Jm2GFYRe-Z1Keudk-DftsJfBdg'
TRADING_API_KEY = 'YOUR_TRADING_API_KEY'
TRADING_API_SECRET = 'YOUR_TRADING_API_SECRET'
